### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by slayer** [GoogleContainerTools/kaniko#1271]
```
 INFO[0000] Using dockerignore file: /builds/xxx/yyy/.dockerignore 
 panic: runtime error: index out of range [0] with length 0
 goroutine 1 [running]:
 github.com/GoogleContainerTools/kaniko/pkg/executor.CalculateDependencies(0xc0008fe090, 0x1, 0x1, 0x3133c00, 0xc0008a1530, 0x0, 0x1, 0xc0008fe090)
 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:516 +0xfd4
 github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild(0x3133c00, 0x1, 0x0, 0x0, 0x7)
 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:593 +0x241
 github.com/GoogleContainerTools/kaniko/cmd/executor/cmd.glob..func2(0x311c000, 0xc000146c40, 0x0, 0x7)
 	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/cmd/root.go:107 +0x12b
 github.com/spf13/cobra.(*Command).execute(0x311c000, 0xc00003a090, 0x7, 0x7, 0x311c000, 0xc00003a090)
 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:830 +0x29d
 github.com/spf13/cobra.(*Command).ExecuteC(0x311c000, 0x0, 0x1a8f8a0, 0xc000042178)
 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
 github.com/spf13/cobra.(*Command).Execute(...)
 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:864
 main.main()
 	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/main.go:26 +0x2d
```

**Comment by tejal29** [comment]
hmm this should not typically happen. Can you share your dockerfile.

**Comment by slayer** [comment]
Yes, actually it was happen when `FROM` is not defined properly

Dockerfile
```
ARG IMAGE
FROM ${IMAGE}
```

and additional `--build-arg IMAGE=${DOCKER_IMAGE}` solves the problem
but IMO error message can be more helpful

**Comment by Tazminia** [comment]
@tejal29 should I take a look at this ?

**Comment by runzexia** [comment]
I also encountered the same problem.
my dockerfile is 
```
FROM debian as debian
RUN \
  export DEBIAN_FRONTEND=noninteractive &&\
  apt-get update &&\
  apt-get install -qq bash-static

FROM golang:1.13-alpine as builder
WORKDIR /workspace
COPY / /workspace/
RUN CGO_ENABLED=0 go install .

FROM alpine
ENTRYPOINT ["/khronos/khronos"]
EXPOSE 8080
COPY --from=debian /bin/bash-static /khronos/bash
COPY --from=builder /go/bin/khronos /khronos/

```

**Comment by tejal29** [comment]
> @tejal29 should I take a look at this ?

Please do @Tazminia . Would appreciate any help here.

**Comment by tim-itwakes** [comment]
> I also encountered the same problem.
> my dockerfile is
> 
> ```
> FROM debian as debian
> RUN \
>   export DEBIAN_FRONTEND=noninteractive &&\
>   apt-get update &&\
>   apt-get install -qq bash-static
> 
> FROM golang:1.13-alpine as builder
> WORKDIR /workspace
> COPY / /workspace/
> RUN CGO_ENABLED=0 go install .
> 
> FROM alpine
> ENTRYPOINT ["/khronos/khronos"]
> EXPOSE 8080
> COPY --from=debian /bin/bash-static /khronos/bash
> COPY --from=builder /go/bin/khronos /khronos/
> ```

maybe the following line is the reason?
```
FROM debian as debian
```

In my case,
it works after I change `FROM composer as composer` to `FROM composer to composerStage`

**Comment by gstolz** [comment]
I'm having the same problem. Using ARG reference in multi-stage seems to be the problem:
- ARG in single-FROM Dockerfile -> OK
- ARG in multi-stage Dockerfile (NodeJS) -> Not OK
- ARG in multi-stage Dockerfile (Go) -> Not OK

**Comment by gstolz** [comment]
Sorry to say this, but in my case it was not a problem of Kaniko! I just did not properly specify the ARG in Dockerfile!
In multi-layer Dockerfile the scope needs to be taken care of as described in the docs and an Stackoverflow article:
https://stackoverflow.com/questions/53681522/multi-stage-dockerfile-arg-before-from-not-substituted
https://docs.docker.com/engine/reference/builder/#arg
https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

**Comment by dankeder** [comment]
I encountered the same problem as well. In my case the problem was the `FROM` statement:
```dockerfile
FROM nginx as nginx
```

A workaround that helped in my case was to use a tagged image:

```dockerfile
FROM nginx:latest as nginx
```

**Comment by neumantm** [comment]
I have the same problem.
I'm using `FROM composer as composer`
The workaround mentioned by @dankeder worked, but I think this should be fixed.

**Comment by vijal-patel** [comment]
is this still an issue? I'm happy to work on it

**Comment by dimaulupov** [comment]
It is still happening.
If you have multi-stage build and have this:
```
FROM golang as golang
```
kaniko fails with this error.

But this line:
```
FROM golang as builder
```
works fine

**Comment by ashish1099** [comment]
I'm still seeing this issue, even without multistage build.
This is my Dockerfile, and I have tried the latest 1.18.0 and 1.9.1 (debug) images

```
FROM example.com/jammy-generic-build:1.0.0
MAINTAINER Ashish Jaiswal <ashish@enableit.dk>

WORKDIR /tmp

RUN apt-get update \
    && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    pandoc \
    texlive-xetex \
    && \
    apt-get autoremove -y \
    && \
    apt-get autoclean -y \

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN rm -fr /var/lib/apt/lists/*

```

**Comment by bouaouda-achraf** [comment]
Reproductible with : 
--build-arg "XX=YY"
instead of : 
--build-arg XX=YY
