### ISSUE TITLE
ImportError: Error relocating /usr/lib/python3.8/site-packages/cv2/cv2.cpython-38-x86_64-linux-gnu.so: cblas_dgemm: symbol not found

### ISSUE THREAD

**Issue by dHannasch** [GoogleContainerTools/kaniko#1605]
**Actual behavior**

Dockerfile builds successfully on Docker Hub but not with Kaniko.

With Kaniko, `import cv2` fails with
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: Error relocating /usr/lib/python3.8/site-packages/cv2/cv2.cpython-38-x86_64-linux-gnu.so: cblas_dgemm: symbol not found
```
http://www.netlib.org/lapack/explore-html/dc/d18/cblas__dgemm_8c_abae9e96e4ce9231245ea09a3f46bdba5.html

**Expected behavior**

The build to work the same in Kaniko as in Docker.

**To Reproduce**
1. Take the Dockerfile from https://github.com/dHannasch/test-install-opencv/blob/master/Dockerfile or https://gitlab.com/dHannasch/test-install-opencv/-/blob/master/Dockerfile.
2. This Dockerfile is being built to https://hub.docker.com/repository/docker/dahanna/test-install-opencv on Docker Hub, and is being built using Kaniko at https://gitlab.com/dHannasch/test-install-opencv. (Credit for the `.gitlab-ci.yml` goes to https://gitlab.com/guided-explorations/containers/kaniko-docker-build, except that I also tried  `--cleanup --cache=false` since that apparently worked for the error-relocating symbol-not-found error in https://github.com/GoogleContainerTools/kaniko/issues/1335. In this case `--cleanup --cache=false` made no difference.)

**Additional Information**
 - Dockerfile
   https://github.com/dHannasch/test-install-opencv/blob/master/Dockerfile
   https://gitlab.com/dHannasch/test-install-opencv/-/blob/master/Dockerfile
 - Build Context
   https://gitlab.com/dHannasch/test-install-opencv
   https://hub.docker.com/repository/docker/dahanna/test-install-opencv
 - Kaniko Image (fully qualified with digest)
   Using docker image sha256:2432b4270607c7fb9f92e5a5e014526e1b1b1837f84abbbb89d79ff89f4dd7a5 for gcr.io/kaniko-project/executor:debug with digest gcr.io/kaniko-project/executor@sha256:e00dfdd4a44097867c8ef671e5a7f3e31d94bd09406dbdfba8a13a63fc6b8060

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag |  with or without `--cache` |
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by dHannasch** [comment]
This still happens with the latest Python 3.9.
