### ISSUE TITLE
SIGSEGV in kaniko/pkg/util.mkdirAllWithPermissions

### ISSUE THREAD

**Issue by gewei2000** [GoogleContainerTools/kaniko#1657]
Kaniko version :  v1.6.0 amd64
command: /kaniko/executor --context . --dockerfile Dockerfile --destination 192.168.5.10/demo/demo:latest

```
INFO[0009] Returning cached image manifest
INFO[0009] Executing 0 build triggers
WARN[0009] maintainer is deprecated, skipping
INFO[0009] Unpacking rootfs as cmd ADD ./target/app.jar app.jar requires it.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x88c694]

goroutine 1 [running]:
github.com/GoogleContainerTools/kaniko/pkg/util.mkdirAllWithPermissions(0xc0002bb810, 0xf, 0x800001fd, 0x0, 0xc, 0x1, 0x1)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/util/fs_util.go:763 +0x474
github.com/GoogleContainerTools/kaniko/pkg/util.ExtractFile(0x2019f56, 0x1, 0xc00040b5e0, 0x22e64e0, 0xc00047e000, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/util/fs_util.go:335 +0xdbc
github.com/GoogleContainerTools/kaniko/pkg/util.GetFSFromLayers(0x2019f56, 0x1, 0xc0001ff820, 0x2, 0x2, 0xc00083ef38, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/util/fs_util.go:196 +0x3b9
github.com/GoogleContainerTools/kaniko/pkg/util.GetFSFromImage(0x2019f56, 0x1, 0x2355220, 0xc0001efa40, 0x2105110, 0x1, 0x1, 0x4, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/util/fs_util.go:132 +0x145
github.com/GoogleContainerTools/kaniko/pkg/executor.(*stageBuilder).build(0xc000c846e0, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:305 +0x35c
github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild(0x30b9680, 0x1, 0x0, 0x0, 0xc0004dc420)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:594 +0x67a
github.com/GoogleContainerTools/kaniko/cmd/executor/cmd.glob..func2(0x30a07a0, 0xc00005c500, 0x0, 0x8)
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/cmd/root.go:118 +0xe8
github.com/spf13/cobra.(*Command).execute(0x30a07a0, 0xc00004c0a0, 0x8, 0x8, 0x30a07a0, 0xc00004c0a0)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x30a07a0, 0xd, 0xc0001c8ea0, 0x0)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/main.go:31 +0x72

```

**Comment by slrz** [comment]
I get the same stack trace but only for some Dockerfiles and/or contexts (and only when running in K8s). Not sure what' exactly triggers the issue.

In any case, the problem doesn't reproduce with images built from current master.

**Comment by zhangguanzhang** [comment]
> I get the same stack trace but only for some Dockerfiles and/or contexts (and only when running in K8s). Not sure what exactly triggers the issue.
> 
> In any case, the problem doesn't reproduce with images built from current master.

how to reproduce this issue

**Comment by cmoulliard** [comment]
Do you still want a test case to verify it ?

**Comment by tiverive** [comment]
Hi, is there any updates on this issue? I'm experiencing the same issue on a multi staged docker image using the kaniko-executor v1.7.0-slim and alpine linux version 3.

`/kaniko/executor --context /calc --no-push`

```
/kaniko/executor --context /calc --no-push
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x874177]

goroutine 1 [running]:
github.com/GoogleContainerTools/kaniko/pkg/util.mkdirAllWithPermissions(0xc00047e5b0, 0xf, 0x800001fd, 0x0, 0xc, 0x1, 0x1)
```

**Comment by tiverive** [comment]
Just want to let others know that by adding the following command to the dockerfile I was able to avoid the error.
rm /var/spool/mail

**Comment by aaron-prindle** [comment]
I believe this was fixed with https://github.com/GoogleContainerTools/kaniko/pull/1813, closing.  Feel free to comment and I can re-open if there is more here
