### ISSUE TITLE
Why is kaniko not keeping bash in the final image?

### ISSUE THREAD

**Issue by tal-zvon** [GoogleContainerTools/kaniko#1895]
If I have a dockerfile like this:

```
FROM python:3.7
CMD ["python"]
```

And use kaniko to create the image with:

```
docker container run \
    --rm \
    -v $PWD:/app \
    --entrypoint="" \
    --privileged \
    registry.gitlab.com/mariuspod/kaniko/executor-debug-arm:latest \
    /kaniko/executor \
        --context /app \
        --dockerfile /app/Dockerfile \
        --destination=test:latest \
        --tarPath=/app/image.tar \
        --no-push

docker load < image.tar
```

The image is created, and contains `/bin/bash`:

```bash
root@raspberrypi:~/test# docker run --rm -it test:latest bash
root@13799f71e9ac:/#
```

This makes sense, because the starting image (python:3.7) contains `/bin/bash`.

If on the other hand I add another, completely unrelated line to the Dockerfile, so it looks like this:

```
FROM python:3.7
RUN mkdir /test
CMD ["python"]
```

Build the image again with the same kaniko command, and run it again with the same command, I get this:

```
root@raspberrypi:~/test# docker run --rm -it test:latest bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.
```

Using python, which IS present in the image, I can tell that the image created doesn't even have `/bin`:

```
root@raspberrypi:~/test# docker run --rm -it test:latest python
>>> from pathlib import Path
>>> for item in Path("/bin").iterdir(): print(item)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/pathlib.py", line 1107, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/bin'
```

Because the python:3.7 image that this build is based on has `/bin/bash`, I would expect the final image to also have `/bin/bash`, but including a `RUN` command in the `Dockerfile` stops this from happening for some reason.

Notes:
  - This is done on a Raspberry Pi 4
  - I can NOT reproduce the issue using the `gcr.io/kaniko-project/executor:debug` image on an x86_64 Intel MacOS
    - `/bin/bash` IS present in the final image, even with the `RUN` command on the mac
  - I can't run `docker build` on the Pi because of lack of privileges, and `--privileged` doesn't work on `docker build`, so I can't confirm if this problem is specific to kaniko or not
  - Running `docker build` on the Mac with the `RUN` command in the dockerfile produces an image that DOES contain `/bin/bash`, as expected

Is this a bug with `registry.gitlab.com/mariuspod/kaniko/executor-debug-arm:latest`? Or am I doing something wrong?

**Comment by tal-zvon** [comment]
The Kaniko version inside the image I was using (`registry.gitlab.com/mariuspod/kaniko/executor-debug-arm:latest`) is v0.17.1. The latest Kaniko appears to be v1.7.0.

Building my own Kaniko image on a Raspberry Pi with the latest Kaniko version didn't end up being as difficult as I expected, and that fixed this issue.
