### ISSUE TITLE
runtime error with MAINTAINER command

### ISSUE THREAD

**Issue by gimler** [GoogleContainerTools/kaniko#446]
**Actual behavior**
```
WARN[0001] maintainer is deprecated, skipping           
07:37:56 [1807] panic: runtime error: invalid memory address or nil pointer dereference
07:37:56 [1807] [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1441e5d]
07:37:56 [1807] 
07:37:56 [1807] goroutine 1 [running]:
07:37:56 [1807] github.com/GoogleContainerTools/kaniko/pkg/executor.(*stageBuilder).build(0xc42061a180, 0xc420477750, 0xa)
07:37:56 [1807] 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:168 +0x40d
07:37:56 [1807] github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild(0x2494600, 0x1, 0x0, 0x0, 0x0)
07:37:56 [1807] 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:317 +0x194
07:37:56 [1807] github.com/GoogleContainerTools/kaniko/cmd/executor/cmd.glob..func2(0x2485280, 0xc42060e120, 0x0, 0x6)
07:37:56 [1807] 	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/cmd/root.go:81 +0x6e
07:37:56 [1807] github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).execute(0x2485280, 0xc4200c0010, 0x6, 0x6, 0x2485280, 0xc4200c0010)
07:37:56 [1807] 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
07:37:56 [1807] github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2485280, 0x0, 0x183c1fb, 0x25)
07:37:56 [1807] 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:852 +0x30a
07:37:56 [1807] github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).Execute(0x2485280, 0xc4205bff78, 0xc4200ac058)
07:37:56 [1807] 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:800 +0x2b
07:37:56 [1807] main.main()
07:37:56 [1807] 	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/main.go:26 +0x2d
```

**Expected behavior**
no runtime error

**To Reproduce**
Dockerfile
```
FROM alpine:3.8

MAINTAINER Gordon Franke <gordon.franke@sap.com>
```

see also #99 

 - Kaniko Image (fully qualified with digest)
gcr.io/kaniko-project/executor:debug 6b5a19050a55

**Comment by priyawadhwa** [comment]
Hey @gimler thanks for opening this bug! It should be fixed now with #447
